package com.xd.commander.aku.utils;

/**
 * @author Administrator 23:10 2018/1/5
 */
public class Constants {
    public static String css = "<style>* {font-size:18px;line-height:25px;} h3{font-size:20px;color:#000;}h2{font-size:25px;color:#000;} h1{font-size:30px;color:#000;} blockquote p{background:#D7D7D7;} p {font-size:20px;color:#000;} td a {color:#3E62A6;min-width:200px;} pre {font-size:9pt;line-height:12pt;font-family:Courier New,Arial;border:1px solid #ddd;border-left:5px solid #6CE26C;background:#f6f6f6;} code{color:#FF4081;background:#EAEAEA;}</style>";
    public static String BMOB_ = "fc845d2c89dcdab10aad9b17d4805f79";
    public static String TRANS_URL = "http://api.fanyi.baidu.com/api/trans/vip/translate";
    public static String APP_ID = "20160424000019521";
    public static String SECURITY_KEY = "Hv8XkkCeQTn5xGBPDYgj";
    public static String[] select ={
            "Id","Name","Stargazers"
    };
    public static final String[] TAGS = {
            "All",
            "2D Engines",
            "3D Engines",
            "9-Patch",
            "Action Bars",
            "Activities",
            "ADB",
            "Advertisements",
            "Analytics",
            "Animations",
            "ANR",
            "AOP",
            "API",
            "APK",
            "APT",
            "Architecture",
            "Audio",
            "Autocomplete",
            "Background Processing",
            "Backward Compatibility",
            "Badges",
            "Bar Codes",
            "Benchmarking",
            "Bitmaps",
            "Bluetooth",
            "Blur Effects",
            "Bread Crumbs",
            "BRMS",
            "Browser Extensions",
            "Build Systems",
            "Bundles",
            "Buttons",
            "Caching",
            "Camera",
            "Canvas",
            "Cards",
            "Carousels",
            "Changelog",
            "Checkboxes",
            "Cloud Storages",
            "Color Analysis",
            "Color Pickers",
            "Colors",
            "Comet/Push",
            "Compass Sensors",
            "Content Providers",
            "Crash Reports",
            "Credit Cards",
            "Credits",
            "CSV",
            "Curl/Flip Effects",
            "Data Binding",
            "Data Generators",
            "Data Structures",
            "Database",
            "Database Browsers",
            "Date & Time Pickers",
            "Debugging",
            "Decompilers",
            "Deep Links",
            "Dependency Injections",
            "Design",
            "Design Patterns",
            "Dex",
            "Dialogs",
            "Distributed Computing",
            "Distribution Platforms",
            "Download Managers",
            "Drawables",
            "Emoji",
            "Emulators",
            "EPUB",
            "Equalizers & Visualizations",
            "Event Buses",
            "Exception Handling",
            "Face Recognition",
            "Feedback & Ratings",
            "File System",
            "File/Directory Choosers",
            "Fingerprint",
            "Floating Action Buttons",
            "Fonts",
            "Forms",
            "Fragments",
            "FRP",
            "FSM",
            "Functional Programming",
            "Gamepads",
            "Games",
            "Gestures",
            "GIF",
            "Glow Pad Views",
            "Gradle Plugins",
            "Graphics",
            "Grid Views",
            "Highlighting",
            "HTML",
            "HTTP Mocking",
            "Icons",
            "IDE",
            "IDE Plugins",
            "Image Croppers",
            "Image Loaders",
            "Image Pickers",
            "Image Processing",
            "Image Views",
            "Instrumentation",
            "Intents",
            "Job Schedulers",
            "JSON",
            "Keyboard",
            "Kotlin",
            "Layouts",
            "List View",
            "List Views",
            "Localization",
            "Location",
            "Lock Patterns",
            "Logcat",
            "Logging",
            "Mails",
            "Maps",
            "Markdown",
            "Mathematics",
            "Maven Plugins",
            "MBaaS",
            "Media",
            "Menus",
            "Messaging",
            "MIME",
            "Mobile Web Frameworks",
            "Native Image Processing",
            "Navigation",
            "NDK",
            "Networking",
            "NFC",
            "NoSQL",
            "Number Pickers",
            "OAuth",
            "Object Mocking",
            "OCR Engines",
            "OpenGL",
            "ORM",
            "Other Pickers",
            "Parallax List Views",
            "Parcelables",
            "Particle Systems",
            "Password Inputs",
            "PDF",
            "Permissions",
            "Physics Engines",
            "Platforms",
            "Plugin Frameworks",
            "Preferences",
            "Progress Indicators",
            "ProGuard",
            "Properties",
            "Protocol Buffer",
            "Pull To Refresh",
            "Purchases",
            "Push/Pull Notifications",
            "QR Codes",
            "Quick Return",
            "Radio Buttons",
            "Range Bars",
            "Ratings",
            "Recycler Views",
            "Resources",
            "REST",
            "Ripple Effects",
            "RSS",
            "Screenshots",
            "Scripting",
            "Scroll Views",
            "SDK",
            "Search Inputs",
            "Security",
            "Sensors",
            "Services",
            "Showcase Views",
            "Signatures",
            "Sliding Panels",
            "Snackbars",
            "SOAP",
            "Social Networks",
            "Spannable",
            "Spinners",
            "Splash Screens",
            "SSH",
            "Static Analysis Tools",
            "Status Bars",
            "Styling",
            "SVG",
            "System",
            "Tags",
            "TDD & BDD",
            "Template Engines",
            "Testing",
            "Testing Tools",
            "Text Formatting",
            "Text Views",
            "Text Watchers",
            "Text-to-Speech",
            "Toasts",
            "Toolkits For Other PL",
            "Tools",
            "Tooltips",
            "TV",
            "Updaters",
            "USB",
            "Utils",
            "Validation",
            "Video",
            "View Adapters",
            "View Pagers",
            "Views",
            "Watch Face",
            "Wearable Data Layer",
            "Weather",
            "Web Tools",
            "Web Views",
            "WebRTC",
            "WebSockets",
            "Wheel Widgets",
            "Wi-Fi",
            "Widgets",
            "Windows",
            "Wizards",
            "XML",
            "XMPP",
            "YAML",
            "ZIP Codes"};
}
